$ANSIBLE_VAULT;1.1;AES256
36383737613163663632643233346661626436666633623061363638373465316537383063323934
6637343631333432363737663935636430663831653836310a646631333566363432303733353236
32303063363737336330306463363166313438376264663761643034303431386533616133313464
3265343831386334330a353032333761343135623661343738656437336163313962353063333736
38633332663133323039313565396331613165303639393236333330376635393031663438356537
37343132356133363731356462303063383734613737383966306162353930303264396131363135
64383936373334383561663831623630323534376334373932393761363936316362333131346633
38323331316361346637383938306136653131663031343432616538313162373265323634356434
37383039333761626436323264623762623134323462303166316339383137323434306663373839
61343533376163623662633232656163616436353237313935356665316337306333623332333763
